version: 2.1

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: 
          command: |
            cd ./delivery-service
            npm install
            npm test
          
workflows:
  build-and-test:
    jobs:
      - test
